# Generated by Django 2.1.4 on 2019-07-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190712_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='手机号'),
        ),
    ]
