# Generated by Django 2.1.4 on 2019-06-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190616_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='youneed_konw',
            new_name='youneed_know',
        ),
    ]
